name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
          key: ${{ runner.os }}-${{ hashFiles('**/*.cabal') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          # can't build docs on ghc-9.2 with cabal-3.8, see
          # - https://github.com/haskell/cabal/issues/8104
          # - https://github.com/haskell/haddock/issues/1582
          ghc-version: 9.4
          cabal-version: 3.8

      - name: Install zookeeper-dev on ubuntu
        run: sudo apt-get update && sudo apt-get install -y libzookeeper-mt-dev

      - name: Publish package
        run: |
          cabal sdist && cabal haddock --enable-documentation --haddock-for-hackage

          tar_file="$(cabal sdist | grep zoovisitor)"
          doc_file="$(cabal haddock --enable-documentation --haddock-for-hackage|grep 'zoovisitor.*docs.tar.gz')"

          echo $tar_file
          echo $doc_file

          cabal upload -u '${{ secrets.HACKAGE_USERNAME }}' -p '${{ secrets.HACKAGE_PASSWORD }}' --publish $tar_file
          cabal upload -u '${{ secrets.HACKAGE_USERNAME }}' -p '${{ secrets.HACKAGE_PASSWORD }}' --publish --doc $doc_file
